language: python
sudo: required
python:
    - "2.7"
env:
    - CKANVERSION=master
    - CKANVERSION=2.4
    - CKANVERSION=2.5
    - CKANVERSION=2.6
    - CKANVERSION=2.7

install:
    - bash bin/travis-build.bash
services:
    - redis-server
    - postgresql
script: sh bin/travis-run.sh
before_install:
    - pip install codecov
after_success:
    - codecov
